### PR TITLE
Frontend: fix placeholders for adding form

### LINKED ISSUE #39: Hidden placeholders on adding
Initial values in goods time form hide placeholder. It's necessary to change initial values.

### PR DESCRIPTION
**Pull request by ImVogl**
Initial values for add new item form was changed from defined values to undefined

### CODE REVIEW

File: Frontend/src/components/inventarisation/InventarisationEditing.tsx [hunk 1]
```diff
@@ -13,9 +13,9 @@ import { badRequestProcessor } from '../../common/utilites/Common';
 export interface INewItem{
     item: string;
     category: string;
-    storage: number;
-    whole: number;
-    retail: number;
+    storage: number | undefined;
```
Comment (PiperMaru13) [inline Frontend/src/components/inventarisation/InventarisationEditing.tsx:16]: Thnx God, its not a null...

Comment (ImVogl) [reply Frontend/src/components/inventarisation/InventarisationEditing.tsx:16]: Your commentary is insignificant.

**Review by PiperMaru13 — APPROVED** [review]
Wonderfully
